volumes:
  jugda_jekyll_data:
    name: jugda_jekyll_data
services:
  jekyll:
    image: jekyll/jekyll:3.8
    command: jekyll serve --watch
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll:cached
      - jugda_jekyll_data:/usr/local/bundle
