services:
  jekyll:
    build: .
    image: jugda/jekyll
    command: jekyll serve --watch --incremental
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll:cached
